+++
date = 2018-08-08T00:00:00  # Schedule page publish date.

title = "Allocation to clonal growth:
approaches and questions"
time_start = 2018-08-02T09:45:00
time_end = 2018-08-02T10:05:00
abstract =""
abstract_short = ""
event = "12th Clonal Plant Symposium"
event_url = "http://www.bowdoin.edu/symposia/clonalplants/index.shtml"
location = "Brunswick, ME"

# Is this a selected talk? (true/false)
selected = false

# Projects (optional).
#   Associate this talk with one or more of your projects.
#   Simply enter the filename of your project file in `content/project/`.
#   Otherwise, set `projects = []`.
projects = []

# Links (optional).
url_pdf = ""
url_slides = ""
url_video = ""
url_code = ""

# Does the content use math formatting?
math = true

# Does the content use source code highlighting?
highlight = true

# Featured image
# Place your image in the `static/img/` folder and reference its filename below, e.g. `image = "example.jpg"`.
[header]
image = "headers/bubbles-wide.jpg"
caption = "My caption :smile:"

+++
